const MAIN_STATES = {
  INITIAL: "INITIAL",
  SELECT_START: "SELECT_START",
  SELECT_COMPLETED: "SELECT_START"
};

const CONTROL_STATES = {
  BTN_CONTROL_ADDED: "BTN_CONTROL_ADDED",
  SELECT_START: "SELECT_START",
  SELECT_COMPLETED: "SELECT_START"
};

export { MAIN_STATES, CONTROL_STATES };
