/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PwcLeafletEntitySelector {
    /**
    * Extended leaflet configuration for pwc-leaflet-entity-selector
    * @prop config.autoAdd: If enabled, auto add control to given map instance. Map should be provided to activate this feature.
    * @prop config.leaflet: Default options for leaflet control
    */
    'config': { autoAdd: boolean; leaflet: {}; };
    'getControl': () => Promise<import("/Users/haldunyildiz/Projects/Parabol Projects/opensource/pwc-leaflet-entity-selector/node_modules/@types/leaflet/index").Control>;
    /**
    * If leaflet map instance provided, auto-add feature will be enabled.
    */
    'map'?: L.Map;
  }
}

declare global {


  interface HTMLPwcLeafletEntitySelectorElement extends Components.PwcLeafletEntitySelector, HTMLStencilElement {}
  var HTMLPwcLeafletEntitySelectorElement: {
    prototype: HTMLPwcLeafletEntitySelectorElement;
    new (): HTMLPwcLeafletEntitySelectorElement;
  };
  interface HTMLElementTagNameMap {
    'pwc-leaflet-entity-selector': HTMLPwcLeafletEntitySelectorElement;
  }
}

declare namespace LocalJSX {
  interface PwcLeafletEntitySelector {
    /**
    * Extended leaflet configuration for pwc-leaflet-entity-selector
    * @prop config.autoAdd: If enabled, auto add control to given map instance. Map should be provided to activate this feature.
    * @prop config.leaflet: Default options for leaflet control
    */
    'config'?: { autoAdd: boolean; leaflet: {}; };
    /**
    * If leaflet map instance provided, auto-add feature will be enabled.
    */
    'map'?: L.Map;
    'onPwcLeafletEntitySelector'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'pwc-leaflet-entity-selector': PwcLeafletEntitySelector;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pwc-leaflet-entity-selector': LocalJSX.PwcLeafletEntitySelector & JSXBase.HTMLAttributes<HTMLPwcLeafletEntitySelectorElement>;
    }
  }
}


